### ISSUE TITLE
Migrate to TypeORM

### ISSUE THREAD

**Issue by zakhenry** [ubiquits/ubiquits#71]
Currently the orm implementation is a abstraction of Sequelize, however this comes with some issues as their model system is not conducive to repository pattern and is not typescript designed so there is some weirdness there.

There is a new ORM in progress called [TypeORM](https://github.com/pleerock/typeorm) which offers nearly every feature required, and in typescript. This will greatly improve velocity to beta.

Currently they only support MySQL, so while we would prefer to use Postgres for the native uuid and schema support it's probably better to just go with MySQL(MariaDB) for the time being while the adapter is [still being written](https://github.com/pleerock/typeorm/issues/10#issuecomment-226985333).
### Considerations
- `@Table` & `@Column` decorators will need to be either renamed or moved to the `DatabaseStore` as they don't make sense on the common isomorphic model (doesn't make sense for the frontend to be registering column/table attributes when it doesn't care). As decorators are just functions, it's probably easy to just rename/move them with new decorators
- No UUID type in mysql - this can be handled (temporarily) with just a varchar column. not idea, but ok for beta
- No schemas - this feature of Postgres was going to be used to separate modules out for easy migrate/destroy. This can be emulated with table name prefixes for MySQL? [Drop tables like](http://stackoverflow.com/a/11053206/515578). Also see [TypeORM naming strategies](https://github.com/pleerock/typeorm/blob/master/docs/naming-strategies.md)

**Comment by pleerock** [comment]
> rename `@Table` & `@Column`

As I understood you want to abstract frontend model from database implementation. But there is no frontend model. There is also no a backend model. There is a single model that is and frontend and backend model (correct me if I got you wrong). And since its same model it most probably will share its origin between each other. 
Also how do you plan to rename it? Don't think its a good idea for two reasons: first because users will confuse when read orm documentation where there will we different decorators and second - no metter how you rename it - you can't hide that its a database decorators - relations, decorator options will expose what it is anyway.
Btw just to mention that you can also [store schema in separate files](https://github.com/pleerock/typeorm/tree/master/sample/sample24-schemas/schemas). But of course its not as convenient as with decorators.

> No UUID type in mysql - this can be handled (temporarily) with just a varchar column. not idea, but ok for beta

I think in the future orm can implement **id generation strategies**. These strategies can include uuid, auto increment and other strategies generation by orm.

**Comment by zakhenry** [comment]
Hey @pleerock yep you've understood the architecture correctly - models are common to frontend and backend (same source).

I agree with the concern about renaming decorators, however I'm thinking that it may be a bit more than renaming. Due to how the ModelStore pattern works, the storage engine implementation could be anything from relational db, to nosql, to redis to localstorage, remote api etc etc. The implementation is also platform independent. For that reason the model should be defining more abstract properties like `@StoredProperty` in place of column. (For the database store that would be the `@Column` decorator).

It's true that no matter what I name it, there will be some bias towards the datatypes looking like database columns, but in general, between database, redis, nosql, localstorage and json, the greatest granularity is required for relational databases, and so every "column" type can be mapped to those datatypes.

On UUID's, I don't actually really care about uuid generation - in a distributed infrastructure it's better to have the client generate the uuid than the server. It's also really useful for handling queueing systems as the client can already have the id reference to an object that will (probably) be stored at some point.

Thanks for the input 😄

**Comment by zakhenry** [comment]
Hey @pleerock yep you've understood the architecture correctly - models are common to frontend and backend (same source).

I agree with the concern about renaming decorators, however I'm thinking that it may be a bit more than renaming. Due to how the ModelStore pattern works, the storage engine implementation could be anything from relational db, to nosql, to redis to localstorage, remote api etc etc. The implementation is also platform independent. For that reason the model should be defining more abstract properties like `@StoredProperty` in place of column. (For the database store that would be the `@Column` decorator).

It's true that no matter what I name it, there will be some bias towards the datatypes looking like database columns, but in general, between database, redis, nosql, localstorage and json, the greatest granularity is required for relational databases, and so every "column" type can be mapped to those datatypes.

On UUID's, I don't actually really care about uuid generation - in a distributed infrastructure it's better to have the client generate the uuid than the server. It's also really useful for handling queueing systems as the client can already have the id reference to an object that will (probably) be stored at some point.

Thanks for the input 😄
