### ISSUE TITLE
Implement validation class-validator

### ISSUE THREAD

**Issue by zakhenry** [ubiquits/ubiquits#72]
For class validation @pleerock has implemented an awesome typescript package - https://github.com/pleerock/class-validator
### Checklist
- [x] Install class-validator
- [x] Implement default validations on the `ResourceController`

~~\- [ ] Create `@ValidatePayload(m:ModelStatic, options?: ValidationOptions)` middleware decorator~~ moved to #83 
~~\- [ ] Verify that the `@Validate` custom decorator works with our DI. (https://github.com/pleerock/class-validator#using-service-container)~~ Can't think of a simple method. Discussion moved to #84
~~\- [ ] Consider extending class-validator to handle async validation~~ Will do later - #86

**Comment by pleerock** [comment]
before extending class validator make sure you aren't implementing a common-scenario behaviour that can be included in class validator itself.

**Comment by zakhenry** [comment]
Yea sure - in this case I'm remapping the internal exception to my own exceptions that extends an HttpRestException, which has a few extra methods specific to my framework.

**Comment by zakhenry** [comment]
@pleerock yea I'll fork & PR if its a feature that's not dependent on this platform. Custom async validation  is probably a good one - might be a common case to need to interact with a database or third party service to validate something. Probably opening a can of worms here as it would have a number of ramifications - only `validateAsync` could work with an async validation function
