### ISSUE TITLE
Allow for dependencies to be injected into custom @Validate decorators

### ISSUE THREAD

**Issue by zakhenry** [ubiquits/ubiquits#84]
See https://github.com/pleerock/class-validator#custom-validation-classes - there is the option to create custom validator classes, but they won't be resolved by the injector.

A improvement to class-validator is probably needed to implement a `CustomValidatorProvider` or something which allows the implementer to define their own dependency injection etc.

Something like the following implementation

``` ts
import {registerCustomValidatorProvider, ValidatorInterface} from 'class-validator';
import {coreInjector} from '@ubiquits/core/server';

// this should go in 'class-validator'
interface ValidatorStatic<T extends ValidatorInterface> {
  new(...dependencies:any[]): T;
}

registerCustomValidatorProvider((validatorClass: ValidatorStatic):ValidatorInterface => {
  return coreInjector.get(validatorClass);
});

```
### Considerations

For ubiquits there are two independent injectors (browser and server). This bootstrapping of class-validator would have to happen twice. But then how would it resolve which to use as the same instance of `MetadataStorage` is needed...this may be becoming outside the scope of what class-validator should handle.

@pleerock any thoughts?

**Comment by zakhenry** [comment]
Wait, is this as simple as calling 

``` ts
import validator from 'class-validation';
import {coreInjector} from '@ubiquits/core/server';
//[...]
validator.container = coreInjector;
validator.validateAsync(model).then([...])

```

??

**Comment by pleerock** [comment]
so, did that work?

**Comment by zakhenry** [comment]
Yep! Way easier than anticipated :)

**Comment by pleerock** [comment]
haha nice
