### ISSUE TITLE
Async validators

### ISSUE THREAD

**Issue by zakhenry** [ubiquits/ubiquits#86]
Currently async validators are not supported by [class-validator](https://github.com/pleerock/class-validator/issues/12)

Once this is implemented, update the docs and add tests to verify.

**Comment by zakhenry** [comment]
🎉  @pleerock has implemented async functionality (along with a lot of extra goodies) in https://github.com/pleerock/class-validator/pull/14 All that is needed now is documentation update.

**Comment by pleerock** [comment]
I have merged branch to the master. I made most of things I wanted to do. Basically what is left is to test everything + a bit more test coverage

**Comment by zakhenry** [comment]
Awesome thanks, and nice work 😄
